# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Run Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run_tests:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Required Local NPM Packages
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Required Local NPM Packages
      run: npm install knex@0.95.4
  
    - name: Create Docker Test Environment
      run: docker-compose up -d

    - name: Run Database Migrations
      run: npm runMigrations
